# 数据源配置
spring:
#  data:
#    mongodb:
#      uri: mongodb://10.5.0.200:27017/ljcx_frame
  redis:
    database: 0
    host: 10.5.0.200
    port: 6379
    password: lanjiang2019 # 密码（默认为空）
    timeout: 6000  # 连接超时时长（毫秒）
    ssl: false
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 0       # 连接池中的最小空闲连接

  activemq:
    broker-url: tcp://10.5.0.200:61616
    user: admin
    password: admin
    in-memory: true
    #true表示使用连接池
    pool:
      # 如果此处设置为true,需要加activemq-pool的依赖包，否则会自动配置失败，报JmsMessagingTemplate注入失败
      enabled: true
      #连接池最大连接数
      max-connections: 5
      #空闲的连接过期时间，默认为30秒
      idle-timeout: 30000
      #强制的连接过期时间，与idleTimeout的区别在于：idleTimeout是在连接空闲一段时间失效，而expiryTimeout不管当前连接的情况，只要达到指定时间就失效。默认为0，never
      #expiry-timeout: 0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://10.5.0.200:3306/ljcx_frame_offline?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: ljcx_frame
        password: lanjiang2019
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username:
        login-password:
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
log:
  level:
    root: info
    my: info
  file: E:/app_logs/platform/platform-server.log
  maxsize: 30MB
